[package]
name = "delta_encode_derive"
version = "0.1.0"
authors = ["Matthew Collins <me@thinkof.name>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
bitflags = "1.0.4"
quote = "0.6.11"
proc-macro2 = "0.4.26"

[dependencies.syn]
version = "0.15.26"
features = ["extra-traits"]